matrix:
  include:
    - language: python
      python: 3.6
      before_script:
        - cd server/server
      script:
        - python ./manage.py test

    - language: node_js
      before_script:
        - cd client
      script:
        - yarn test