dist: xenial
matrix:
  include:
    - language: python
      python: 3.6
      before_script:
        - cd server/server
      script:
        - pip install -Ur ../requirements.txt
        - python ./manage.py test

    - language: node_js
      node_js: 8
      before_script:
        - cd client
      script:
        - yarn install
        - yarn test